---
- hosts: jenkins_group
  become: true

- name: JENKINS-PASSTOKEN | Get initial authentication token
  shell: 'cat /var/lib/jenkins/secrets/initialAdminPassword'
  register: admin_auth_token

- name: JENKINS-CTEDENTIALS | Create CRUMB authentication request
  uri:
    url: 'http://localhost:{{ jenkins_port }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: admin
    password: '{{ admin_auth_token.stdout }}'
    force_basic_auth: yes
    return_content: yes
  register: crumb

- name: JENKINS-CTEDENTIALS | Add Jenkins administration account
  uri:
    method: POST
    url: 'http://localhost:{{ jenkins_port }}/securityRealm/createAccountByAdmin'
    user: admin
    password: '{{ admin_auth_token.stdout }}'
    force_basic_auth: yes
    follow_redirects: all
    headers:
      Jenkins-Crumb: '{{ crumb.content.split(":")[1] }}'
      Cookie: '{{ crumb.set_cookie }}'
    body: 'username={{ jenkins_user }}&password1={{ jenkins_pass }}&password2={{ jenkins_pass }}&fullname={{ jenkins_fullname }}&email={{ jenkins_email }}'
    
    
    
    /////// in progress
    
- uri:
    url: 'http://{{ HostName }}:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: admin
    password: admin
    force_basic_auth: yes
    return_content: yes
  register: crumb

- uri:
    method: POST
    url: 'http://{{ HostName }}:8080/credentials/store/system/domain/_/createCredentials'
    user: admin
    password: admin
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "credential_id_here",
          "username": "username_here",
          "password": "password_here",
          "description": "My new credentials",
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }
